# Generated by Django 5.2.8 on 2025-11-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmer",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="programmer",
            name="age",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
